image: node:13.7

stages:
  - test

variables:
  THEME_ID: '7630013536'
  PASSWORD: 7779592d571fed2fe6e7bd7626973400
  STORE: halfhelix-ci.myshopify.com

before_script:
  - echo $THEME_ID
  - echo $PASSWORD
  - echo $STORE
  - npm i -g lerna
  - lerna bootstrap

tests:
  type: test
  script:
    - npm ci
    - npm run test
  except:
    - master
    - production

lint:
  type: test
  script:
    - cd ./packages/theme/basic-test
    - npm i
    - node ../../cli/cli.js lint
  except:
    - master
    - production

build:
  type: test
  script:
    - cd ./packages/theme/basic-test
    - npm i
    - node ../../cli/cli.js build
  except:
    - master
    - production

deploy:
  type: test
  script:
    - cd ./packages/theme/basic-test
    - npm i
    - node ../../cli/cli.js deploy
  except:
    - master
    - production
