image: node:13.7

stages:
  - test

before_script:
  - npm i -g lerna
  - lerna bootstrap

tests:
  type: test
  script:
    - npm ci
    - npm run test
  except:
    - master
    - production

exec:
  type: test
  script:
    - cd ./packages/theme/basic-test
    - npm i
    - node ../../cli/cli.js lint
  except:
    - master
    - production
